<a href="https://colab.research.google.com/github/adityakalra581/Data-Science/blob/master/Deep%20Learning/Tensorflow_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## [TENSORFLOW TUTORIAL](https://www.tensorflow.org/api_docs)

- The Code is Updated as Tensorflow 2.x

In [0]:
import pandas as pd
import numpy as np
import tensorflow as tf


In [11]:
tf.__version__

'2.2.0-rc2'

Writing and running programs in TensorFlow has the following steps:

1. Create Tensors (variables) that are not yet executed/evaluated. 
2. Write operations between those Tensors.
3. Initialize your Tensors. 
4. No need to create Sessions now.


In [8]:
x= tf.constant(2,name='x')
y= tf.constant(5,name='y')
z=tf.add(x,y)
print(z)


tf.Tensor(7, shape=(), dtype=int32)


In [10]:
x= tf.constant(2,name='x')
y= tf.constant(5,name='y')
z=tf.add(x,y)
tf.print(z)

7


Let's Calculate the Loss:
$$loss = \mathcal{L}(\hat{y}, y) = (\hat y^{(i)} - y^{(i)})^2 \tag{1}$$

In [15]:
X=tf.constant(36,name='X')
Y=tf.constant(39,name="Y")
loss=(tf.subtract(X,Y)**2)   
print("The Loss is equal to : ")
tf.print(loss) 
  

The Loss is equal to : 
9


Multiplying two constants!!!

In [17]:
a = tf.constant(2)
b = tf.constant(10)
c = tf.multiply(a,b)

## Printing the Tensor
print(c)

## Printing the Value inside a Tensor.
tf.print(c)

tf.Tensor(20, shape=(), dtype=int32)
20


just checking

Let's create a single layer single neuron neural network.

In [0]:
import tensorflow.keras as keras
import numpy as np

model = keras.Sequential([keras.layers.Dense(units=1,input_shape=[1])])
model.compile(optimizer='sgd',loss='mean_squared_error')

x = np.array([-1,1,3,5,7,9],dtype=int)
y=np.array([-3,0,5,9,13,17],dtype=int)

model.fit(x,y,epochs = 500)


In [23]:
print(model.predict([10]))

[[19.079174]]


In [0]:
## Clearly the pattern between the two arrays is y=2x-1
## So the correct answer for x=10 is y=19.
## For 500 epochs the loss is quite minimized.
## I tried 10,100,500 
# And with 500 i got the best results. 

In [0]:
import tensorflow as tf

## [tf.subtract](https://www.tensorflow.org/api_docs/python/tf/math/subtract)

* It's mentioned tf.math.subtract but use tf.subtract instead.
* NOTE: Subtract supports broadcasting. More about broadcasting here

- Args:
- x: A Tensor. Must be one of the following types: 

bfloat16, half, float32, float64, uint8, int8, uint16, int16, int32, int64, complex64, complex128.

- y: A Tensor. Must have the same type as x.


In [25]:
a = [32,32,16]
b = [28,28,8]

sub = tf.subtract(a,b)
print("The Resultant Tensor is:")
tf.print(sub)

The Resultant Tensor is:
[4 4 8]


In [28]:
## Multidimensional:

x = [[[10,12,23],
     [45,56,67],
     [12,23,22]]]

y = [[[2,3,4],
      [1,2,3],
      [5,7,8]]]

result = tf.subtract(x,y)
print("The Resultant Tensor is:")
tf.print(result)

The Resultant Tensor is:
[[[8 9 19]
  [44 54 64]
  [7 16 14]]]
